
import java.awt.Dimension;
import javax.swing.ImageIcon;
import java.awt.*;
import java.net.URL;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Hui Li
 */
public class ImageJPanel extends javax.swing.JPanel 
{

    /**
     * Creates new form ImageJPanel
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    Graphics g = null;
    Image image = null;
    // End of variables declaration//GEN-END:variables
	
    public ImageJPanel() 
    {
        initComponents();
        URL imgURL=getClass().getResource("map.jpg");
        image =new ImageIcon(imgURL).getImage();
        Dimension size = new Dimension(image.getWidth(this), image.getHeight(this));
        setSize(size);
    }

    @Override
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
    
    @Override
    public void update(Graphics g)
    {
      g.drawImage(image, 0, 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
}
